language: go
go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "stable"
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - if [ "${TRAVIS_GO_VERSION}" = "stable" ]; then script/setup/dev-tools; fi
  - go build -i .
  - if [ "${TRAVIS_GO_VERSION}" = "stable" ]; then echo running check scripts; make check; fi
  - go build
  - go test -v ./...
